### ISSUE TITLE
Is it 2D/3D dataset?

### ISSUE THREAD

**Issue by innat** [BMEII-AI/RadImageNet#2]
Is RadImagenNet 2D dataset or 3D dataset? 
The 4 pre-trained weights come with 2D network. But I'm curious if this dataset has 3D version with corresponding 3D pre-trained weights!

**Comment by xmei123** [comment]
this version of RadImageNet is 2D based. We are working on 3D weights now. We'll update this repo once the 3D version is ready.

**Comment by xyf9474** [comment]
> this version of RadImageNet is 2D based. We are working on 3D weights now. We'll update this repo once the 3D version is ready.

It's a really useful work for AI in medical images,Hope to have 3D weights and pytorch weights version like ‘pth’... at your earliest convenience.By the way, If it is convenient, could you upload the version and other information of tensorflow/pythoch，witch are Important for environment building.
