### ISSUE TITLE
Access to subset of dataset

### ISSUE THREAD

**Issue by masoudnick** [BMEII-AI/RadImageNet#4]
Hi,
I am a master's student in artificial intelligence, the subject of my thesis is the classification of brain tumors using MRI images.
My question is, is it possible to access the MRI brain images that are in your dataset?

**Comment by masoudnick** [comment]
Yes, thanks.

**Comment by dhudsmith** [comment]
I have filled out the request form but have not received any response. Is the form still monitored?

**Comment by dhudsmith** [comment]
@xmei123, thanks for your reply. I filled out the form here: https://www.radimagenet.com/copy-of-home-1, but I never received a data use agreement. I confirmed that it's not in my junk folder. Perhaps I should try again with a different email?

**Comment by masoudnick** [comment]
Hi @xmei123 
I sent my signed DUA but still didn't receive any link :(
Full name : Masoud Nickparvar
Email : masoudnick85@gmail.com
