### ISSUE TITLE
 Performance of public models and access to train, validation, and test splits.

### ISSUE THREAD

**Issue by dhudsmith** [BMEII-AI/RadImageNet#8]
First of all, think you for making this dataset public. I am excited to see what fruit it will bear in the medical imaging community. 

In the spirit of imagenet, can you share the train, validation, and test splits used in the published results? Apart from facilitating comparisons between groups, all images from an individual patient should be kept in a single split. The paper mentions that the authors were careful to split the data this way, but, as far as I can tell, the published data does not include the metadata needed to reproduce this step.  

Also, could the aggregate test set performance (perhaps top-1 and top-5 accuracy) be published here on github to accompany the published models? While I agree that the application to small downstream datasets is more important, having the radimagenet test set performance would facilitate methodological comparison. 

Thanks again!

**Comment by lzl199704** [comment]
Thank you for your suggestion. You can request the splited dataset via Google Drive. Here is the link https://drive.google.com/drive/folders/1FUir_Y_kbQZWih1TMVf9Sz8Pdk9NF2Ym?usp=share_link

**Comment by dhudsmith** [comment]
Thanks; this is a big help. Any chance of seeing the performance measures for the released models?

**Comment by lzl199704** [comment]
The RadImageNet InceptionResNet-v2, ResNet50, DenseNet121, and InceptionV3
models achieved top-1 accuracies of 74.0%, 72.3%, 73.1%, and 73.2%,
respectively and top-5 accuracies of 94.3%, 94.1%, 96.1%, and 92.7%,
respectively.

Zelong

**Comment by dhudsmith** [comment]
Thanks, @lzl199704!
